### PR TITLE
Typo in php.ini mssql.compatibility_mode

### PR DESCRIPTION
**Pull request by Petrox**
Bad:
mssql.compatability_mode = Off

Good:
mssql.compatibility_mode = Off

### CODE REVIEW

**Comment by geerlingguy** [comment]
Heh, from: https://bugs.php.net/bug.php?id=53941 (see also: https://bugs.php.net/bug.php?id=69052).

But I like spelling things correctly, so I'll merge this in :).

**Comment by Petrox** [comment]
But if the php config option name has the typo we have to stay that way,
and my pull request is invalid then...

Also is there :facepalm here?

**Comment by geerlingguy** [comment]
@Petrox - It works either way (the typo is basically an alias to the correct spelling). So either way works as well as the other, at least as far back as PHP 5.2 (probably earlier).

**Comment by geerlingguy** [comment]
Hmm... digging deeper it looks like 5.4 still has `compatability` only, so I'm going to revert the commit... since some people still use it :P

**Comment by Petrox** [comment]
Thank you, and sorry. :)

**Comment by geerlingguy** [comment]
No problem! If it weren't for PHP 5.4, I'd rather have it spelled correctly :P

**Pull request merged**
