### PR TITLE
Issue #48: Fix opcache/apc always enabled regardless of config

### PR DESCRIPTION
**Pull request by oxyc**
Havent actually tested but according to the `bool` implementation it should solve it. https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/core.py#L115

### CODE REVIEW

**Comment by oxyc** [comment]
Okay so I was on the wrong track entirely. This needs more thought, which is why it hasnt been tackled before I guess.

**Comment by oxyc** [comment]
Works for Ubuntu but not Centos. This might not be the correct approach anyways...

**Comment by oxyc** [comment]
Works for Ubuntu but not Centos. This might not be the correct approach anyways...

**Comment by geerlingguy** [comment]
Should be fixed via #131.

**Pull request closed without merging**
