### PR TITLE
Enables repos for Debian apt distro

### PR DESCRIPTION
**Pull request by dustinalan**
Worked for Centos/Yum but not on Debian/Ubuntu/Apt

### CODE REVIEW

**Comment by geerlingguy** [comment]
If you need a more current apt PPA for Ubuntu (or a different repo for other distros), then the best way to use that is to add a separate task in `pre_tasks` that runs prior to this role, for example, here's how Drupal VM does it:

https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/tasks/init-debian.yml#L23-L33

**Comment by dustinalan** [comment]
Nice, so many ways to do the same thing :+1:

**Comment by dustinalan** [comment]
However, the variable `php_enablerepo` is unused with Ubuntu, which I think needs a comment here:

https://github.com/geerlingguy/ansible-role-php/blob/master/defaults/main.yml#L3

I like the drupal options between the 3 releases, thanks for that.

**Comment by geerlingguy** [comment]
@dustinalan - Good idea! It was documented in the main README file, but it would help to also document it in defaults, so I've done it there.

**Comment by dustinalan** [comment]
Keep up the good work! Learned a lot reading through your playbooks :-) :+1:

**Pull request closed without merging**
