### PR TITLE
Allow extra settings per pool, fix #350

### LINKED ISSUE #350: Unable to set `pm.status_path`
Title says it all, really; the current template and vars don't allow you to set `pm.status_path` for a pool, unless I'm missing something obvious — which is far from impossible.

Is this an actual decision or just something that simply never came up and that you're willing to receive a PR for?

### PR DESCRIPTION
**Pull request by steinbrueckri**

### CODE REVIEW

**Comment by shakalandy** [comment]
Could you please take a look at this one @geerlingguy ?
It's a follow up from the discussion in #350 - thanks!

**Comment by BapRx** [comment]
Hey @geerlingguy sorry to bother you, if those changes look OK for you, could you please merge and tag a new version? Thanks!

**Comment by steinbrueckri** [comment]
Bump

**Comment by steinbrueckri** [comment]
Bump

**Comment by steinbrueckri** [comment]
Bump

**Comment by geerlingguy** [comment]
Re-testing

**Comment by steinbrueckri** [comment]
Ok will check asap 🙇‍♂️

**Comment by geerlingguy** [comment]
Still getting some fails :(

**Comment by steinbrueckri** [comment]
@geerlingguy Finally I was able to find the "Bug".

**Comment by steinbrueckri** [comment]
@geerlingguy What is not the way to go? You merged #395 before this PR. In my option, PR #367 is more flexible then #395. But know there are merge conflicts? How should I deal with this or do you just want to close this PR?

**Comment by steinbrueckri** [comment]
> @geerlingguy What is not the way to go? You merged #395 before this PR. In my option, PR #367 is more flexible then #395. But know there are merge conflicts? How should I deal with this or do you just want to close this PR? 

?

**Pull request closed without merging**
