### PR TITLE
Change `is not defined` => `is undefined` per the Ansible docs.

### PR DESCRIPTION
**Pull request by christophermancini**
Resolves v2.2 undefined errors.

### CODE REVIEW

**Comment by geerlingguy** [comment]
`is not defined` should still work fine; it's probably more a matter of variables being undefined due to a skipped include file that's statically included. See also: https://github.com/ansible/ansible/issues/17065

I have a feeling that adding `static: no` to the includes will fix this area—check out https://github.com/geerlingguy/ansible-role-php/commit/8e227e5bf22335742b837b29b16285d3cb86cc84

**Comment by geerlingguy** [comment]
(This is in 3.4.1, btw).

**Comment by christophermancini** [comment]
@geerlingguy thanks, that fixed the issue and it is working properly in 16.04 again. :)

**Comment by geerlingguy** [comment]
Perfect!

**Pull request closed without merging**
